using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ToolNexus.Infrastructure.Data.IdentityMigrations;

/// <inheritdoc />
public partial class FixIdentityAutoIncrementIds : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        if (!ActiveProvider.Contains("Npgsql", System.StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        migrationBuilder.Sql(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'AspNetUserClaims'
                        AND column_name = 'Id'
                        AND is_identity = 'NO'
                        AND (column_default IS NULL OR column_default NOT LIKE 'nextval(%')
                ) THEN
                    ALTER TABLE "AspNetUserClaims"
                    ALTER COLUMN "Id"
                    ADD GENERATED BY DEFAULT AS IDENTITY;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'AspNetRoleClaims'
                        AND column_name = 'Id'
                        AND is_identity = 'NO'
                        AND (column_default IS NULL OR column_default NOT LIKE 'nextval(%')
                ) THEN
                    ALTER TABLE "AspNetRoleClaims"
                    ALTER COLUMN "Id"
                    ADD GENERATED BY DEFAULT AS IDENTITY;
                END IF;
            END $$;
            """);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        if (!ActiveProvider.Contains("Npgsql", System.StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        migrationBuilder.Sql(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'AspNetUserClaims'
                        AND column_name = 'Id'
                        AND is_identity = 'YES'
                ) THEN
                    ALTER TABLE "AspNetUserClaims"
                    ALTER COLUMN "Id"
                    DROP IDENTITY;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'AspNetRoleClaims'
                        AND column_name = 'Id'
                        AND is_identity = 'YES'
                ) THEN
                    ALTER TABLE "AspNetRoleClaims"
                    ALTER COLUMN "Id"
                    DROP IDENTITY;
                END IF;
            END $$;
            """);
    }
}
