namespace ToolNexus.Domain;

/// <summary>
/// Defines the contract for analyzing CSS assets and returning structured reports.
/// </summary>
public interface ICssIntelligenceEngine
{
    /// <summary>
    /// Analyzes CSS assets described by the supplied request.
    /// </summary>
    /// <param name="request">The analysis request payload.</param>
    /// <param name="cancellationToken">A token used to cancel the analysis operation.</param>
    /// <returns>A result containing report details and generated warnings.</returns>
    ValueTask<CssAnalysisResult> AnalyzeAsync(
        CssAnalysisRequest request,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Represents input settings and source metadata for a CSS analysis run.
/// </summary>
public sealed record CssAnalysisRequest
{
    /// <summary>
    /// Gets the logical name of the analysis run.
    /// </summary>
    public string Name { get; init; } = string.Empty;

    /// <summary>
    /// Gets the source CSS file paths included in the analysis scope.
    /// </summary>
    public IReadOnlyList<string> SourceFiles { get; init; } = Array.Empty<string>();

    /// <summary>
    /// Gets options controlling the analysis behavior.
    /// </summary>
    public CssIntelligenceOptions Options { get; init; } = new();
}

/// <summary>
/// Represents the complete output of a CSS intelligence run.
/// </summary>
public sealed record CssAnalysisResult
{
    /// <summary>
    /// Gets the primary report generated by the analysis.
    /// </summary>
    public CssAnalysisReport Report { get; init; } = new();

    /// <summary>
    /// Gets warnings produced by the analysis.
    /// </summary>
    public IReadOnlyList<CssWarning> Warnings { get; init; } = Array.Empty<CssWarning>();
}

/// <summary>
/// Represents the aggregate report for a CSS analysis run.
/// </summary>
public sealed record CssAnalysisReport
{
    /// <summary>
    /// Gets the UTC timestamp when the report was generated.
    /// </summary>
    public DateTimeOffset GeneratedAtUtc { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Gets per-file analysis details.
    /// </summary>
    public IReadOnlyList<CssFileReport> Files { get; init; } = Array.Empty<CssFileReport>();

    /// <summary>
    /// Gets cross-file selector usage details.
    /// </summary>
    public IReadOnlyList<CssSelectorReport> Selectors { get; init; } = Array.Empty<CssSelectorReport>();
}

/// <summary>
/// Represents analysis details for an individual CSS file.
/// </summary>
public sealed record CssFileReport
{
    /// <summary>
    /// Gets the analyzed file path.
    /// </summary>
    public string FilePath { get; init; } = string.Empty;

    /// <summary>
    /// Gets selector-level details discovered in the file.
    /// </summary>
    public IReadOnlyList<CssSelectorReport> Selectors { get; init; } = Array.Empty<CssSelectorReport>();

    /// <summary>
    /// Gets warnings raised for this file.
    /// </summary>
    public IReadOnlyList<CssWarning> Warnings { get; init; } = Array.Empty<CssWarning>();
}

/// <summary>
/// Represents usage and metadata for a single CSS selector.
/// </summary>
public sealed record CssSelectorReport
{
    /// <summary>
    /// Gets the selector text.
    /// </summary>
    public string Selector { get; init; } = string.Empty;

    /// <summary>
    /// Gets the number of times the selector appears in scope.
    /// </summary>
    public int OccurrenceCount { get; init; }

    /// <summary>
    /// Gets a value indicating whether the selector is classified as a utility selector.
    /// </summary>
    public bool IsUtilitySelector { get; init; }

    /// <summary>
    /// Gets source file paths where the selector appears.
    /// </summary>
    public IReadOnlyList<string> SourceFiles { get; init; } = Array.Empty<string>();
}

/// <summary>
/// Represents a warning produced during CSS analysis.
/// </summary>
public sealed record CssWarning
{
    /// <summary>
    /// Gets a stable warning code.
    /// </summary>
    public string Code { get; init; } = string.Empty;

    /// <summary>
    /// Gets the warning message.
    /// </summary>
    public string Message { get; init; } = string.Empty;

    /// <summary>
    /// Gets the warning category or severity label.
    /// </summary>
    public string Severity { get; init; } = string.Empty;

    /// <summary>
    /// Gets an optional associated file path.
    /// </summary>
    public string? FilePath { get; init; }

    /// <summary>
    /// Gets an optional associated selector.
    /// </summary>
    public string? Selector { get; init; }
}

/// <summary>
/// Defines configuration options for CSS analysis operations.
/// </summary>
public sealed record CssIntelligenceOptions
{
    /// <summary>
    /// Gets a value indicating whether duplicated selectors should be detected.
    /// </summary>
    public bool DetectDuplicateSelectors { get; init; } = true;

    /// <summary>
    /// Gets a value indicating whether utility selector classification should be attempted.
    /// </summary>
    public bool ClassifyUtilitySelectors { get; init; } = true;

    /// <summary>
    /// Gets file path patterns that should be excluded from analysis.
    /// </summary>
    public IReadOnlyList<string> ExcludedPathPatterns { get; init; } = Array.Empty<string>();

    /// <summary>
    /// Gets the maximum number of warnings to emit.
    /// </summary>
    public int WarningLimit { get; init; } = 500;
}
