using Microsoft.EntityFrameworkCore;
using ToolNexus.Infrastructure.Content.Entities;
using ToolNexus.Infrastructure.Data;

namespace ToolNexus.Api.Services.SEO;

public sealed class AiSeoContentGenerator(ToolNexusContentDbContext dbContext)
{
    public async Task<AiSeoContentResult?> GenerateAndStoreAsync(int toolDefinitionId, CancellationToken cancellationToken = default)
    {
        var tool = await dbContext.ToolDefinitions
            .AsNoTracking()
            .SingleOrDefaultAsync(x => x.Id == toolDefinitionId, cancellationToken);

        if (tool is null)
        {
            return null;
        }

        var result = Generate(tool);

        var content = await dbContext.ToolContents
            .Include(x => x.Features)
            .Include(x => x.Examples)
            .Include(x => x.Faq)
            .SingleOrDefaultAsync(x => x.Slug == tool.Slug, cancellationToken);

        if (content is null)
        {
            content = new ToolContentEntity
            {
                Slug = tool.Slug,
                Title = tool.Name,
                SeoTitle = BuildSeoTitle(tool.Name),
                SeoDescription = BuildSeoDescription(result.Overview),
                Intro = result.Overview,
                LongDescription = result.Overview,
                Keywords = BuildKeywords(tool),
                RowVersion = NewRowVersionToken()
            };

            dbContext.ToolContents.Add(content);
        }
        else
        {
            content.Title = tool.Name;
            content.SeoTitle = BuildSeoTitle(tool.Name);
            content.SeoDescription = BuildSeoDescription(result.Overview);
            content.Intro = result.Overview;
            content.LongDescription = result.Overview;
            content.Keywords = BuildKeywords(tool);
            content.Features.Clear();
            content.Examples.Clear();
            content.Faq.Clear();
            content.RowVersion = NewRowVersionToken();
        }

        var featureSortOrder = 0;
        foreach (var feature in result.Features)
        {
            content.Features.Add(new ToolFeatureEntity
            {
                Value = feature,
                SortOrder = featureSortOrder++
            });
        }

        var exampleSortOrder = 0;
        foreach (var example in result.Examples)
        {
            content.Examples.Add(new ToolExampleEntity
            {
                Title = Truncate(example.Title, 160),
                Input = example.Input,
                Output = example.Output,
                SortOrder = exampleSortOrder++
            });
        }

        var faqSortOrder = 0;
        foreach (var faq in result.Faq)
        {
            content.Faq.Add(new ToolFaqEntity
            {
                Question = Truncate(faq.Question, 300),
                Answer = Truncate(faq.Answer, 2000),
                SortOrder = faqSortOrder++
            });
        }

        await dbContext.SaveChangesAsync(cancellationToken);
        return result;
    }

    private static AiSeoContentResult Generate(ToolDefinitionEntity tool)
    {
        var actions = ParseActions(tool.ActionsCsv);
        var primaryAction = actions.FirstOrDefault() ?? "transform content";

        var overview = $"{tool.Name} is an AI-powered {tool.Category.ToLowerInvariant()} tool that helps teams {primaryAction}. " +
            "It is designed for fast, reliable results with a streamlined workflow and production-ready output.";

        var features = new List<string>
        {
            $"AI-guided {tool.Category.ToLowerInvariant()} workflow for {tool.Name}.",
            $"Automates repetitive tasks such as {string.Join(", ", actions.Take(3))}.",
            "Produces consistent outputs suitable for operational and business use.",
            "Simple input-output model that integrates into existing pipelines."
        };

        var examples = new List<AiSeoExample>
        {
            new(
                Title: $"Generate {tool.Name} output from a basic request",
                Input: $"Use {tool.Name} to {primaryAction} for a small sample payload.",
                Output: $"A structured result generated by {tool.Name} with cleaned output and actionable details."),
            new(
                Title: $"Batch processing with {tool.Name}",
                Input: $"Run {tool.Name} across multiple records for {tool.Category.ToLowerInvariant()} automation.",
                Output: "Batch-ready outputs with uniform formatting and predictable structure.")
        };

        var faq = new List<AiSeoFaq>
        {
            new(
                Question: $"What is {tool.Name} used for?",
                Answer: $"{tool.Name} is used to {primaryAction} with AI assistance for faster and more consistent results."),
            new(
                Question: $"Can {tool.Name} handle production workloads?",
                Answer: $"Yes. {tool.Name} is designed for repeatable execution patterns that fit production workflows."),
            new(
                Question: $"Who should use {tool.Name}?",
                Answer: $"Teams, developers, and operators who need dependable {tool.Category.ToLowerInvariant()} automation can use {tool.Name}.")
        };

        return new AiSeoContentResult(overview, features, examples, faq);
    }

    private static List<string> ParseActions(string actionsCsv)
        => actionsCsv
            .Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Take(5)
            .ToList();

    private static string BuildSeoTitle(string name)
        => Truncate($"{name} AI Tool | ToolNexus", 200);

    private static string BuildSeoDescription(string overview)
        => Truncate(overview, 320);

    private static string BuildKeywords(ToolDefinitionEntity tool)
    {
        var keywords = new List<string> { tool.Name, tool.Category, "AI tool", "automation", "ToolNexus" };
        keywords.AddRange(ParseActions(tool.ActionsCsv));
        return Truncate(string.Join(", ", keywords.Distinct(StringComparer.OrdinalIgnoreCase)), 500);
    }

    private static byte[] NewRowVersionToken() => Guid.NewGuid().ToByteArray();

    private static string Truncate(string value, int maxLength)
    {
        if (string.IsNullOrEmpty(value) || value.Length <= maxLength)
        {
            return value;
        }

        return value[..maxLength];
    }
}

public sealed record AiSeoContentResult(
    string Overview,
    IReadOnlyCollection<string> Features,
    IReadOnlyCollection<AiSeoExample> Examples,
    IReadOnlyCollection<AiSeoFaq> Faq);

public sealed record AiSeoExample(string Title, string Input, string Output);
public sealed record AiSeoFaq(string Question, string Answer);
