// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolNexus.Infrastructure.Data;

#nullable disable

namespace ToolNexus.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ToolNexusContentDbContext))]
    [Migration("20260223173001_AddConcurrencyTokens")]
    partial class AddConcurrencyTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AdminAuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditDeadLetterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuditEventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeadLetteredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("jsonb");

                    b.Property<string>("ErrorSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FinalAttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstFailedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("open");

                    b.Property<Guid>("OutboxId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AuditEventId");

                    b.HasIndex("OutboxId")
                        .IsUnique();

                    b.HasIndex("Destination", "DeadLetteredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_dead_letter_destination");

                    b.HasIndex("OperatorStatus", "DeadLetteredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_dead_letter_status_time");

                    b.ToTable("audit_dead_letter", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHashSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadRedacted")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("SourceIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .IsDescending()
                        .HasDatabaseName("idx_audit_events_occurred_at");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("idx_audit_events_trace");

                    b.HasIndex("Action", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_events_action");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_events_tenant");

                    b.HasIndex("ActorType", "ActorId", "OccurredAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_audit_events_actor");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditOutboxEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("AuditEventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AuditEventId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_outbox_idempotency_key");

                    b.HasIndex("LeaseExpiresAtUtc")
                        .HasDatabaseName("idx_audit_outbox_lease");

                    b.HasIndex("DeliveryState", "NextAttemptAtUtc")
                        .HasDatabaseName("idx_audit_outbox_sched");

                    b.HasIndex("Destination", "AuditEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_outbox_destination_event");

                    b.ToTable("audit_outbox", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.DailyToolMetricsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgDurationMs")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalExecutions")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalPayloadSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToolSlug", "DateUtc")
                        .IsUnique();

                    b.ToTable("DailyToolMetrics");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolAnomalySnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToolSlug", "DateUtc", "Type")
                        .IsUnique();

                    b.ToTable("ToolAnomalySnapshots");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ToolCategories");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ToolContents");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolDefinitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionsCsv")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ToolDefinitions");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolExampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolExamples");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolExecutionEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PayloadSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("ToolSlug");

                    b.ToTable("ToolExecutionEvents");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolExecutionPolicyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExecutionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxInputSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRequestsPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("BLOB");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToolDefinitionId")
                        .IsUnique();

                    b.HasIndex("ToolSlug")
                        .IsUnique();

                    b.ToTable("ToolExecutionPolicies");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolFaqEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolFaqs");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolFeatureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolFeatures");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolRelatedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelatedSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolRelated");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolStepEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolSteps");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolUseCaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolUseCases");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditDeadLetterEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.AuditEventEntity", "AuditEvent")
                        .WithMany()
                        .HasForeignKey("AuditEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.AuditOutboxEntity", "Outbox")
                        .WithOne("DeadLetter")
                        .HasForeignKey("ToolNexus.Infrastructure.Content.Entities.AuditDeadLetterEntity", "OutboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditEvent");

                    b.Navigation("Outbox");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditOutboxEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.AuditEventEntity", "AuditEvent")
                        .WithMany("OutboxEntries")
                        .HasForeignKey("AuditEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditEvent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolExampleEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("Examples")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolFaqEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("Faq")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolFeatureEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("Features")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolRelatedEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("RelatedTools")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolStepEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("Steps")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolUseCaseEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("UseCases")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditEventEntity", b =>
                {
                    b.Navigation("OutboxEntries");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditOutboxEntity", b =>
                {
                    b.Navigation("DeadLetter");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("Faq");

                    b.Navigation("Features");

                    b.Navigation("RelatedTools");

                    b.Navigation("Steps");

                    b.Navigation("UseCases");
                });
#pragma warning restore 612, 618
        }
    }
}
