// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToolNexus.Infrastructure.Data;

#nullable disable

namespace ToolNexus.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ToolNexusContentDbContext))]
    [Migration("20260225232324_AddCapabilityMarketplaceRegistry")]
    partial class AddCapabilityMarketplaceRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AdminAuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("AfterJson")
                        .HasColumnType("text");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AdminIdentityUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("admin_identity_users", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditDeadLetterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuditEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_event_id");

                    b.Property<DateTime>("DeadLetteredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("jsonb")
                        .HasColumnName("error_details");

                    b.Property<string>("ErrorSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_summary");

                    b.Property<int>("FinalAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("final_attempt_count");

                    b.Property<DateTime>("FirstFailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_failed_at_utc");

                    b.Property<string>("OperatorId")
                        .HasColumnType("text")
                        .HasColumnName("operator_id");

                    b.Property<string>("OperatorNote")
                        .HasColumnType("text")
                        .HasColumnName("operator_note");

                    b.Property<string>("OperatorStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("open")
                        .HasColumnName("operator_status");

                    b.Property<Guid>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AuditEventId");

                    b.HasIndex("OutboxId")
                        .IsUnique();

                    b.HasIndex("Destination", "DeadLetteredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_dead_letter_destination");

                    b.HasIndex("OperatorStatus", "DeadLetteredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_dead_letter_status_time");

                    b.ToTable("audit_dead_letter", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadHashSha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_hash_sha256");

                    b.Property<string>("PayloadRedacted")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_redacted");

                    b.Property<string>("RequestId")
                        .HasColumnType("text")
                        .HasColumnName("request_id");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_status");

                    b.Property<int>("SchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("schema_version");

                    b.Property<IPAddress>("SourceIp")
                        .HasColumnType("inet")
                        .HasColumnName("source_ip");

                    b.Property<string>("TargetId")
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .IsDescending()
                        .HasDatabaseName("idx_audit_events_occurred_at");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("idx_audit_events_trace");

                    b.HasIndex("Action", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_events_action");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_events_tenant");

                    b.HasIndex("ActorType", "ActorId", "OccurredAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_audit_events_actor");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditOutboxEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("AuditEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_event_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at_utc");

                    b.Property<string>("DeliveryState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delivery_state");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("text")
                        .HasColumnName("lease_owner");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AuditEventId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_outbox_idempotency_key");

                    b.HasIndex("LeaseExpiresAtUtc")
                        .HasDatabaseName("idx_audit_outbox_lease");

                    b.HasIndex("DeliveryState", "NextAttemptAtUtc")
                        .HasDatabaseName("idx_audit_outbox_sched");

                    b.HasIndex("Destination", "AuditEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_outbox_destination_event");

                    b.ToTable("audit_outbox", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.CapabilityRegistryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("authority");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("capability_id");

                    b.Property<int>("ComplexityTier")
                        .HasColumnType("integer")
                        .HasColumnName("complexity_tier");

                    b.Property<int>("InstallationState")
                        .HasColumnType("integer")
                        .HasColumnName("installation_state");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions_json");

                    b.Property<bool>("PolicyExecutionEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("policy_execution_enabled");

                    b.Property<string>("PolicyVersionToken")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("policy_version_token");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider");

                    b.Property<string>("RuntimeLanguage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("runtime_language");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("snapshot_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("SyncedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("tool_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityId")
                        .IsUnique()
                        .HasDatabaseName("ux_capability_registry_capability_id");

                    b.HasIndex("SyncedAtUtc")
                        .HasDatabaseName("idx_capability_registry_synced_at_utc");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("idx_capability_registry_tool_id");

                    b.ToTable("capability_registry", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.DailyToolMetricsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgDurationMs")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("DateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FailureCount")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxDurationMs")
                        .HasColumnType("bigint");

                    b.Property<long>("SuccessCount")
                        .HasColumnType("bigint");

                    b.Property<string>("ToolSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("TotalExecutions")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalPayloadSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ToolSlug", "DateUtc")
                        .IsUnique();

                    b.ToTable("DailyToolMetrics");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ExecutionAuthorityDecisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AdmissionAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("admission_allowed");

                    b.Property<string>("AdmissionReason")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("admission_reason");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("authority");

                    b.Property<string>("DecisionSource")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("decision_source");

                    b.Property<Guid>("ExecutionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_run_id");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionRunId")
                        .IsUnique();

                    b.ToTable("execution_authority_decisions", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ExecutionConformanceResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExecutionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_run_id");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<int>("IssueCount")
                        .HasColumnType("integer")
                        .HasColumnName("issue_count");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("issues_json");

                    b.Property<string>("NormalizedStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_status");

                    b.Property<bool>("WasNormalized")
                        .HasColumnType("boolean")
                        .HasColumnName("was_normalized");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionRunId")
                        .IsUnique();

                    b.ToTable("execution_conformance_results", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ExecutionRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("adapter_name");

                    b.Property<string>("AdapterResolutionStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("adapter_resolution_status");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("authority");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("capability");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("correlation_id");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error_type");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("execution_mode");

                    b.Property<int>("PayloadSize")
                        .HasColumnType("integer")
                        .HasColumnName("payload_size");

                    b.Property<string>("RuntimeLanguage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("runtime_language");

                    b.Property<bool>("ShadowExecution")
                        .HasColumnType("boolean")
                        .HasColumnName("shadow_execution");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("TenantId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tool_id");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_execution_runs_correlation_id");

                    b.HasIndex("ExecutedAtUtc")
                        .HasDatabaseName("idx_execution_runs_executed_at_utc");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_execution_runs_tenant_id");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("idx_execution_runs_tool_id");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("idx_execution_runs_trace_id");

                    b.ToTable("execution_runs", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ExecutionSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("authority");

                    b.Property<string>("ConformanceVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("conformance_version");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("ExecutionCapability")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("execution_capability");

                    b.Property<Guid>("ExecutionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_run_id");

                    b.Property<Guid>("GovernanceDecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("governance_decision_id");

                    b.Property<string>("PolicySnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("policy_snapshot_json");

                    b.Property<string>("RuntimeLanguage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("runtime_language");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionRunId")
                        .IsUnique();

                    b.HasIndex("GovernanceDecisionId")
                        .HasDatabaseName("idx_execution_snapshots_governance_decision_id");

                    b.HasIndex("SnapshotId")
                        .HasDatabaseName("idx_execution_snapshots_snapshot_id");

                    b.ToTable("execution_snapshots", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.GovernanceDecisionEntity", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("approved_by");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("authority");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("capability_id");

                    b.Property<string>("DecisionReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("decision_reason");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("policy_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tool_id");

                    b.HasKey("DecisionId");

                    b.HasIndex("PolicyVersion")
                        .HasDatabaseName("idx_governance_decisions_policy_version");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("idx_governance_decisions_timestamp_utc");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("idx_governance_decisions_tool_id");

                    b.ToTable("governance_decisions", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.RuntimeIncidentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime>("FirstOccurredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastOccurredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Stack")
                        .HasColumnType("text");

                    b.Property<string>("ToolSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("LastOccurredUtc");

                    b.HasIndex("ToolSlug");

                    b.ToTable("RuntimeIncidents");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolAnomalySnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("DateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ToolSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ToolSlug", "DateUtc", "Type")
                        .IsUnique();

                    b.ToTable("ToolAnomalySnapshots");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ToolCategories");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bytea");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ToolContents");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolDefinitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionsCsv")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("InputSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OutputSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bytea");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ToolDefinitions");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolExampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolExamples");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolExecutionEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PayloadSize")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("ToolSlug");

                    b.ToTable("ToolExecutionEvents");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolExecutionPolicyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsExecutionEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxInputSize")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRequestsPerMinute")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bytea");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("ToolDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("ToolSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ToolDefinitionId")
                        .IsUnique();

                    b.HasIndex("ToolSlug")
                        .IsUnique();

                    b.ToTable("ToolExecutionPolicies");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolFaqEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolFaqs");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolFeatureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolFeatures");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolQualityScoreEntity", b =>
                {
                    b.Property<string>("ToolId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tool_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<decimal>("ArchitectureScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("architecture_score");

                    b.Property<decimal>("CraftScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("craft_score");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<decimal>("TestCoverageScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("test_coverage_score");

                    b.HasKey("ToolId", "TimestampUtc");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("idx_tool_quality_scores_timestamp_utc");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("idx_tool_quality_scores_tool_id");

                    b.ToTable("tool_quality_scores", (string)null);
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolRelatedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RelatedSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolRelated");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolStepEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolSteps");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolUseCaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolUseCases");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditDeadLetterEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.AuditEventEntity", "AuditEvent")
                        .WithMany()
                        .HasForeignKey("AuditEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.AuditOutboxEntity", "Outbox")
                        .WithOne("DeadLetter")
                        .HasForeignKey("ToolNexus.Infrastructure.Content.Entities.AuditDeadLetterEntity", "OutboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditEvent");

                    b.Navigation("Outbox");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditOutboxEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.AuditEventEntity", "AuditEvent")
                        .WithMany("OutboxEntries")
                        .HasForeignKey("AuditEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditEvent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ExecutionAuthorityDecisionEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ExecutionRunEntity", "ExecutionRun")
                        .WithOne("AuthorityDecision")
                        .HasForeignKey("ToolNexus.Infrastructure.Content.Entities.ExecutionAuthorityDecisionEntity", "ExecutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRun");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ExecutionConformanceResultEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ExecutionRunEntity", "ExecutionRun")
                        .WithOne("Conformance")
                        .HasForeignKey("ToolNexus.Infrastructure.Content.Entities.ExecutionConformanceResultEntity", "ExecutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRun");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ExecutionSnapshotEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ExecutionRunEntity", "ExecutionRun")
                        .WithOne("Snapshot")
                        .HasForeignKey("ToolNexus.Infrastructure.Content.Entities.ExecutionSnapshotEntity", "ExecutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.GovernanceDecisionEntity", "GovernanceDecision")
                        .WithMany("ExecutionSnapshots")
                        .HasForeignKey("GovernanceDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExecutionRun");

                    b.Navigation("GovernanceDecision");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolExampleEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("Examples")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolFaqEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("Faq")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolFeatureEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("Features")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolRelatedEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("RelatedTools")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolStepEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("Steps")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolUseCaseEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("UseCases")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditEventEntity", b =>
                {
                    b.Navigation("OutboxEntries");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.AuditOutboxEntity", b =>
                {
                    b.Navigation("DeadLetter");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ExecutionRunEntity", b =>
                {
                    b.Navigation("AuthorityDecision")
                        .IsRequired();

                    b.Navigation("Conformance")
                        .IsRequired();

                    b.Navigation("Snapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.GovernanceDecisionEntity", b =>
                {
                    b.Navigation("ExecutionSnapshots");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("Faq");

                    b.Navigation("Features");

                    b.Navigation("RelatedTools");

                    b.Navigation("Steps");

                    b.Navigation("UseCases");
                });
#pragma warning restore 612, 618
        }
    }
}
