using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ToolNexus.Infrastructure.Data.Migrations
{
    public partial class AddToolExecutionEvents : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ToolExecutionEvents",
                columns: table => new
                {
                    Id = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ToolSlug = table.Column<string>(type: "TEXT", maxLength: 120, nullable: false),
                    TimestampUtc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    DurationMs = table.Column<long>(type: "INTEGER", nullable: false),
                    Success = table.Column<bool>(type: "INTEGER", nullable: false),
                    ErrorType = table.Column<string>(type: "TEXT", maxLength: 200, nullable: true),
                    PayloadSize = table.Column<int>(type: "INTEGER", nullable: false),
                    ExecutionMode = table.Column<string>(type: "TEXT", maxLength: 20, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ToolExecutionEvents", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ToolExecutionEvents_TimestampUtc",
                table: "ToolExecutionEvents",
                column: "TimestampUtc");

            migrationBuilder.CreateIndex(
                name: "IX_ToolExecutionEvents_ToolSlug",
                table: "ToolExecutionEvents",
                column: "ToolSlug");

            if (ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql(@"ALTER TABLE ""ToolExecutionEvents"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "ToolExecutionEvents");
        }
    }
}
