using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ToolNexus.Infrastructure.Data;

#nullable disable

namespace ToolNexus.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ToolNexusContentDbContext))]
    [Migration("20260227000000_AddToolAnomalySnapshots")]
    public partial class AddToolAnomalySnapshots : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ToolAnomalySnapshots",
                columns: table => new
                {
                    Id = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ToolSlug = table.Column<string>(type: "TEXT", maxLength: 120, nullable: false),
                    DateUtc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    Type = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    Severity = table.Column<string>(type: "TEXT", maxLength: 16, nullable: false),
                    Description = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ToolAnomalySnapshots", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ToolAnomalySnapshots_ToolSlug_DateUtc_Type",
                table: "ToolAnomalySnapshots",
                columns: new[] { "ToolSlug", "DateUtc", "Type" },
                unique: true);

            if (ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql(@"ALTER TABLE ""ToolAnomalySnapshots"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "ToolAnomalySnapshots");
        }
    }
}
