using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ToolNexus.Infrastructure.Data.Migrations
{
    [DbContextAttribute(typeof(ToolNexusContentDbContext))]
    [Migration("20260223010000_AddToolDefinitions")]
    public partial class AddToolDefinitions : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql(
                    """
                    CREATE TABLE IF NOT EXISTS "ToolDefinitions" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                        "Name" character varying(200) NOT NULL,
                        "Slug" character varying(120) NOT NULL,
                        "Description" character varying(2000) NOT NULL,
                        "Category" character varying(120) NOT NULL,
                        "Status" character varying(20) NOT NULL,
                        "Icon" character varying(120) NOT NULL,
                        "SortOrder" integer NOT NULL,
                        "ActionsCsv" character varying(500) NOT NULL,
                        "InputSchema" text NOT NULL,
                        "OutputSchema" text NOT NULL,
                        "UpdatedAt" timestamp with time zone NOT NULL,
                        CONSTRAINT "PK_ToolDefinitions" PRIMARY KEY ("Id")
                    );
                    """);

                migrationBuilder.Sql(
                    """
                    CREATE UNIQUE INDEX IF NOT EXISTS "IX_ToolDefinitions_Slug"
                    ON "ToolDefinitions" ("Slug");
                    """);

                return;
            }

            migrationBuilder.CreateTable(
                name: "ToolDefinitions",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Name = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    Slug = table.Column<string>(type: "TEXT", maxLength: 120, nullable: false),
                    Description = table.Column<string>(type: "TEXT", maxLength: 2000, nullable: false),
                    Category = table.Column<string>(type: "TEXT", maxLength: 120, nullable: false),
                    Status = table.Column<string>(type: "TEXT", maxLength: 20, nullable: false),
                    Icon = table.Column<string>(type: "TEXT", maxLength: 120, nullable: false),
                    SortOrder = table.Column<int>(type: "INTEGER", nullable: false),
                    ActionsCsv = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false),
                    InputSchema = table.Column<string>(type: "TEXT", nullable: false),
                    OutputSchema = table.Column<string>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ToolDefinitions", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ToolDefinitions_Slug",
                table: "ToolDefinitions",
                column: "Slug",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "ToolDefinitions");
        }
    }
}
