using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ToolNexus.Infrastructure.Data;

#nullable disable

namespace ToolNexus.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ToolNexusContentDbContext))]
    [Migration("20260226000000_AddDailyToolMetrics")]
    public partial class AddDailyToolMetrics : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "DailyToolMetrics",
                columns: table => new
                {
                    Id = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ToolSlug = table.Column<string>(type: "TEXT", maxLength: 120, nullable: false),
                    DateUtc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    TotalExecutions = table.Column<long>(type: "INTEGER", nullable: false),
                    SuccessCount = table.Column<long>(type: "INTEGER", nullable: false),
                    FailureCount = table.Column<long>(type: "INTEGER", nullable: false),
                    AvgDurationMs = table.Column<double>(type: "REAL", nullable: false),
                    MaxDurationMs = table.Column<long>(type: "INTEGER", nullable: false),
                    TotalPayloadSize = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DailyToolMetrics", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_DailyToolMetrics_ToolSlug_DateUtc",
                table: "DailyToolMetrics",
                columns: new[] { "ToolSlug", "DateUtc" },
                unique: true);

            if (ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql(@"ALTER TABLE ""DailyToolMetrics"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "DailyToolMetrics");
        }
    }
}
