using System.Text;

namespace ToolNexus.Infrastructure.Data.Migrations;

internal static class PostgresMigrationSafety
{
    public const string BooleanStrategy = "boolean";
    public const string InetStrategy = "inet";

    public static string EnsureIdentityColumn(string tableName, string columnName = "Id")
        => EnsureIdentityColumnSafe(tableName, columnName);

    public static string EnsureIdentityColumnSafe(string tableName, string columnName = "Id")
        => $"""
           DO $$
           BEGIN
               IF to_regclass('{EscapeSqlLiteral(tableName)}') IS NULL THEN
                   RETURN;
               END IF;

               IF EXISTS (
                   SELECT 1
                   FROM information_schema.columns
                   WHERE table_schema = current_schema()
                     AND table_name = '{EscapeSqlLiteral(tableName)}'
                     AND column_name = '{EscapeSqlLiteral(columnName)}'
                     AND is_identity = 'NO')
               THEN
                   EXECUTE format(
                       'ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
                       '{EscapeSqlLiteral(tableName)}',
                       '{EscapeSqlLiteral(columnName)}');
               END IF;
           END $$;
           """;

    public static string SafeIdentityNoOpIfExists(string tableName, string columnName = "Id")
        => EnsureIdentityColumnSafe(tableName, columnName);

    public static string SafeNoOpIfIdentityExists(string tableName, string columnName = "Id")
        => EnsureIdentityColumnSafe(tableName, columnName);

    public static string DropConstraintIfExists(string tableName, string constraintName)
        => SafeDropConstraintIfExists(tableName, constraintName);

    public static string SafeDropConstraintIfExists(string tableName, string constraintName)
        => $"""
           DO $$
           BEGIN
               IF to_regclass('{EscapeSqlLiteral(tableName)}') IS NOT NULL THEN
                   ALTER TABLE {QuoteIdentifier(tableName)} DROP CONSTRAINT IF EXISTS {QuoteIdentifier(constraintName)};
               END IF;
           END $$;
           """;

    public static string AddColumnIfMissing(string tableName, string columnName, string columnDefinitionSql)
        => SafeAddColumnIfMissing(tableName, columnName, columnDefinitionSql);

    public static string SafeAddColumnIfMissing(string tableName, string columnName, string columnDefinitionSql)
        => $"""
           DO $$
           BEGIN
               IF to_regclass('{EscapeSqlLiteral(tableName)}') IS NOT NULL
                  AND NOT EXISTS (
                       SELECT 1
                       FROM information_schema.columns
                       WHERE table_schema = current_schema()
                         AND table_name = '{EscapeSqlLiteral(tableName)}'
                         AND column_name = '{EscapeSqlLiteral(columnName)}')
               THEN
                   EXECUTE format(
                       'ALTER TABLE %I ADD COLUMN %I {columnDefinitionSql}',
                       '{EscapeSqlLiteral(tableName)}',
                       '{EscapeSqlLiteral(columnName)}');
               END IF;
           END $$;
           """;

    public static string SafeConvertToBoolean(string tableName, string columnName)
        => SafeConvertColumn(tableName, columnName, BooleanStrategy);

    public static string SafeConvertColumnToBoolean(string tableName, string columnName)
        => SafeConvertToBoolean(tableName, columnName);

    public static string SafeConvertToInet(string tableName, string columnName)
        => SafeConvertColumn(tableName, columnName, InetStrategy);

    public static string SafeConvertColumn(string tableName, string columnName, string strategy)
        => strategy switch
        {
            BooleanStrategy => BuildBooleanConversionSql(tableName, columnName),
            InetStrategy => BuildInetConversionSql(tableName, columnName),
            _ => throw new ArgumentOutOfRangeException(nameof(strategy), strategy, "Unsupported migration conversion strategy")
        };

    public static string EnsureTableExists(string tableName, string createSql)
        => $"""
           DO $$
           BEGIN
               IF to_regclass('{EscapeSqlLiteral(tableName)}') IS NULL THEN
                   {createSql}
               END IF;
           END $$;
           """;


    public static string SafeAddForeignKeyIfMissing(string tableName, string constraintName, string foreignKeySql)
        => $"""
           DO $$
           BEGIN
               IF to_regclass('{EscapeSqlLiteral(tableName)}') IS NOT NULL
                  AND NOT EXISTS (
                      SELECT 1
                      FROM pg_constraint constraint_entry
                      INNER JOIN pg_class relation_entry ON relation_entry.oid = constraint_entry.conrelid
                      INNER JOIN pg_namespace namespace_entry ON namespace_entry.oid = relation_entry.relnamespace
                      WHERE constraint_entry.conname = '{EscapeSqlLiteral(constraintName)}'
                        AND relation_entry.relname = '{EscapeSqlLiteral(tableName)}'
                        AND namespace_entry.nspname = current_schema())
               THEN
                   EXECUTE 'ALTER TABLE {QuoteIdentifier(tableName)} ADD CONSTRAINT {QuoteIdentifier(constraintName)} {foreignKeySql}';
               END IF;
           END $$;
           """;

    public static string SafeDropTableIfExists(string tableName)
        => $"DROP TABLE IF EXISTS {QuoteIdentifier(tableName)};";
    private static string BuildBooleanConversionSql(string tableName, string columnName)
        => BuildMultiStepConversion(
            tableName,
            columnName,
            "boolean",
            conversionExpressionTemplate: "CASE WHEN lower(%I::text) IN ('true','1','yes','y','success') THEN TRUE WHEN lower(%I::text) IN ('false','0','no','n','fail') THEN FALSE ELSE FALSE END");

    private static string BuildInetConversionSql(string tableName, string columnName)
        => BuildMultiStepConversion(
            tableName,
            columnName,
            "inet",
            conversionExpressionTemplate: "CASE WHEN %I::text ~ '^(\\d{1,3}\\.){3}\\d{1,3}$' THEN %I::inet ELSE NULL END");

    private static string BuildMultiStepConversion(string tableName, string columnName, string targetType, string conversionExpressionTemplate)
        => $"""
           DO $$
           DECLARE
               table_exists boolean;
               column_exists boolean;
               temp_column_exists boolean;
               current_data_type text;
               nullable_state text;
               temp_column_name text := '{EscapeSqlLiteral(columnName)}__safe_target';
               conversion_sql text;
           BEGIN
               SELECT to_regclass('{EscapeSqlLiteral(tableName)}') IS NOT NULL INTO table_exists;
               IF NOT table_exists THEN
                   RETURN;
               END IF;

               SELECT EXISTS (
                   SELECT 1
                   FROM information_schema.columns
                   WHERE table_schema = current_schema()
                     AND table_name = '{EscapeSqlLiteral(tableName)}'
                     AND column_name = '{EscapeSqlLiteral(columnName)}') INTO column_exists;

               SELECT EXISTS (
                   SELECT 1
                   FROM information_schema.columns
                   WHERE table_schema = current_schema()
                     AND table_name = '{EscapeSqlLiteral(tableName)}'
                     AND column_name = temp_column_name) INTO temp_column_exists;

               IF NOT column_exists THEN
                   IF temp_column_exists THEN
                       EXECUTE format('ALTER TABLE %I RENAME COLUMN %I TO %I', '{EscapeSqlLiteral(tableName)}', temp_column_name, '{EscapeSqlLiteral(columnName)}');
                   END IF;

                   RETURN;
               END IF;

               SELECT data_type, is_nullable
               INTO current_data_type, nullable_state
               FROM information_schema.columns
               WHERE table_schema = current_schema()
                 AND table_name = '{EscapeSqlLiteral(tableName)}'
                 AND column_name = '{EscapeSqlLiteral(columnName)}';

               IF current_data_type = '{EscapeSqlLiteral(targetType)}' THEN
                   RETURN;
               END IF;

               IF NOT temp_column_exists THEN
                   EXECUTE format('ALTER TABLE %I ADD COLUMN %I {targetType}', '{EscapeSqlLiteral(tableName)}', temp_column_name);
               END IF;

               conversion_sql := format('{EscapeSqlLiteral(conversionExpressionTemplate)}', '{EscapeSqlLiteral(columnName)}', '{EscapeSqlLiteral(columnName)}');
               EXECUTE format('UPDATE %I SET %I = ' || conversion_sql, '{EscapeSqlLiteral(tableName)}', temp_column_name);

               EXECUTE format('ALTER TABLE %I DROP COLUMN %I', '{EscapeSqlLiteral(tableName)}', '{EscapeSqlLiteral(columnName)}');
               EXECUTE format('ALTER TABLE %I RENAME COLUMN %I TO %I', '{EscapeSqlLiteral(tableName)}', temp_column_name, '{EscapeSqlLiteral(columnName)}');

               IF nullable_state = 'NO' THEN
                   EXECUTE format('ALTER TABLE %I ALTER COLUMN %I SET NOT NULL', '{EscapeSqlLiteral(tableName)}', '{EscapeSqlLiteral(columnName)}');
               END IF;
           END $$;
           """;

    private static string QuoteIdentifier(string identifier)
    {
        var parts = identifier.Split('.', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
        var builder = new StringBuilder();

        for (var index = 0; index < parts.Length; index++)
        {
            if (index > 0)
            {
                builder.Append('.');
            }

            builder.Append('"');
            builder.Append(parts[index].Replace("\"", "\"\"", StringComparison.Ordinal));
            builder.Append('"');
        }

        return builder.ToString();
    }

    private static string EscapeSqlLiteral(string value)
        => value.Replace("'", "''", StringComparison.Ordinal);
}
