using System.Text;

namespace ToolNexus.Infrastructure.Data.Migrations;

internal static class PostgresMigrationSafety
{
    public static string EnsureIdentityColumn(string tableName, string columnName = "Id")
        => EnsureIdentityColumnSafe(tableName, columnName);

    public static string EnsureIdentityColumnSafe(string tableName, string columnName = "Id")
        => SafeNoOpIfIdentityExists(tableName, columnName);

    public static string SafeIdentityNoOpIfExists(string tableName, string columnName = "Id")
        => SafeNoOpIfIdentityExists(tableName, columnName);

    public static string SafeNoOpIfIdentityExists(string tableName, string columnName = "Id")
        => $"""
           DO $$
           BEGIN
               IF to_regclass('{EscapeSqlLiteral(tableName)}') IS NOT NULL
                  AND EXISTS (
                      SELECT 1
                      FROM information_schema.columns
                      WHERE table_schema = current_schema()
                        AND table_name = '{EscapeSqlLiteral(tableName)}'
                        AND column_name = '{EscapeSqlLiteral(columnName)}'
                        AND is_identity = 'NO')
               THEN
                   EXECUTE format(
                       'ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
                       '{EscapeSqlLiteral(tableName)}',
                       '{EscapeSqlLiteral(columnName)}');
               END IF;
           END $$;
           """;

    public static string DropConstraintIfExists(string tableName, string constraintName)
        => SafeDropConstraintIfExists(tableName, constraintName);

    public static string SafeDropConstraintIfExists(string tableName, string constraintName)
        => $"""
           DO $$
           BEGIN
               IF to_regclass('{EscapeSqlLiteral(tableName)}') IS NOT NULL THEN
                   ALTER TABLE {QuoteIdentifier(tableName)} DROP CONSTRAINT IF EXISTS {QuoteIdentifier(constraintName)};
               END IF;
           END $$;
           """;

    public static string AddColumnIfMissing(string tableName, string columnName, string columnDefinitionSql)
        => SafeAddColumnIfMissing(tableName, columnName, columnDefinitionSql);

    public static string SafeAddColumnIfMissing(string tableName, string columnName, string columnDefinitionSql)
        => $"""
           DO $$
           BEGIN
               IF to_regclass('{EscapeSqlLiteral(tableName)}') IS NOT NULL
                  AND NOT EXISTS (
                       SELECT 1
                       FROM information_schema.columns
                       WHERE table_schema = current_schema()
                         AND table_name = '{EscapeSqlLiteral(tableName)}'
                         AND column_name = '{EscapeSqlLiteral(columnName)}')
               THEN
                   EXECUTE format(
                       'ALTER TABLE %I ADD COLUMN %I {columnDefinitionSql}',
                       '{EscapeSqlLiteral(tableName)}',
                       '{EscapeSqlLiteral(columnName)}');
               END IF;
           END $$;
           """;

    public static string SafeConvertColumnToBoolean(string tableName, string columnName)
        => $"""
           DO $$
           DECLARE
               table_exists boolean;
               column_exists boolean;
               column_data_type text;
               temp_column_name text := '{EscapeSqlLiteral(columnName)}_tmp';
               temp_column_exists boolean;
               nullable_state text;
               default_expression text;
           BEGIN
               SELECT to_regclass('{EscapeSqlLiteral(tableName)}') IS NOT NULL
                 INTO table_exists;

               IF NOT table_exists THEN
                   RETURN;
               END IF;

               SELECT EXISTS (
                          SELECT 1
                          FROM information_schema.columns
                          WHERE table_schema = current_schema()
                            AND table_name = '{EscapeSqlLiteral(tableName)}'
                            AND column_name = '{EscapeSqlLiteral(columnName)}')
                 INTO column_exists;

               SELECT EXISTS (
                          SELECT 1
                          FROM information_schema.columns
                          WHERE table_schema = current_schema()
                            AND table_name = '{EscapeSqlLiteral(tableName)}'
                            AND column_name = temp_column_name)
                 INTO temp_column_exists;

               IF NOT column_exists THEN
                   IF temp_column_exists THEN
                       EXECUTE format(
                           'ALTER TABLE %I RENAME COLUMN %I TO %I',
                           '{EscapeSqlLiteral(tableName)}',
                           temp_column_name,
                           '{EscapeSqlLiteral(columnName)}');
                   END IF;

                   RETURN;
               END IF;

               SELECT data_type, is_nullable, column_default
                 INTO column_data_type, nullable_state, default_expression
                 FROM information_schema.columns
                 WHERE table_schema = current_schema()
                   AND table_name = '{EscapeSqlLiteral(tableName)}'
                   AND column_name = '{EscapeSqlLiteral(columnName)}';

               IF column_data_type = 'boolean' THEN
                   RETURN;
               END IF;

               IF NOT temp_column_exists THEN
                   EXECUTE format(
                       'ALTER TABLE %I ADD COLUMN %I boolean',
                       '{EscapeSqlLiteral(tableName)}',
                       temp_column_name);
               END IF;

               EXECUTE format(
                   'UPDATE %I SET %I = CASE
                        WHEN lower(%I::text) IN (''true'',''1'',''yes'',''y'',''success'') THEN TRUE
                        WHEN lower(%I::text) IN (''false'',''0'',''no'',''n'',''fail'',''failed'') THEN FALSE
                        ELSE FALSE
                    END',
                   '{EscapeSqlLiteral(tableName)}',
                   temp_column_name,
                   '{EscapeSqlLiteral(columnName)}',
                   '{EscapeSqlLiteral(columnName)}');

               EXECUTE format(
                   'ALTER TABLE %I DROP COLUMN %I',
                   '{EscapeSqlLiteral(tableName)}',
                   '{EscapeSqlLiteral(columnName)}');

               EXECUTE format(
                   'ALTER TABLE %I RENAME COLUMN %I TO %I',
                   '{EscapeSqlLiteral(tableName)}',
                   temp_column_name,
                   '{EscapeSqlLiteral(columnName)}');

               IF default_expression IS NOT NULL THEN
                   EXECUTE format(
                       'ALTER TABLE %I ALTER COLUMN %I SET DEFAULT CASE
                            WHEN lower((%s)::text) IN (''true'',''1'',''yes'',''y'',''success'') THEN TRUE
                            WHEN lower((%s)::text) IN (''false'',''0'',''no'',''n'',''fail'',''failed'') THEN FALSE
                            ELSE FALSE
                        END',
                       '{EscapeSqlLiteral(tableName)}',
                       '{EscapeSqlLiteral(columnName)}',
                       default_expression,
                       default_expression);
               END IF;

               IF nullable_state = 'NO' THEN
                   EXECUTE format(
                       'ALTER TABLE %I ALTER COLUMN %I SET NOT NULL',
                       '{EscapeSqlLiteral(tableName)}',
                       '{EscapeSqlLiteral(columnName)}');
               END IF;
           END $$;
           """;

    private static string QuoteIdentifier(string identifier)
    {
        var parts = identifier.Split('.', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
        var builder = new StringBuilder();

        for (var index = 0; index < parts.Length; index++)
        {
            if (index > 0)
            {
                builder.Append('.');
            }

            builder.Append('"');
            builder.Append(parts[index].Replace("\"", "\"\"", StringComparison.Ordinal));
            builder.Append('"');
        }

        return builder.ToString();
    }

    private static string EscapeSqlLiteral(string value)
        => value.Replace("'", "''", StringComparison.Ordinal);
}
