using System.Text;

namespace ToolNexus.Infrastructure.Data.Migrations;

internal static class PostgresMigrationSafety
{
    public static string EnsureIdentityColumn(string tableName, string columnName = "Id")
        => $"""
           DO $$
           BEGIN
               IF EXISTS (
                   SELECT 1
                   FROM pg_attribute attribute
                   JOIN pg_class table_definition
                     ON table_definition.oid = attribute.attrelid
                   JOIN pg_namespace schema_definition
                     ON schema_definition.oid = table_definition.relnamespace
                   WHERE schema_definition.nspname = current_schema()
                     AND table_definition.relname = '{EscapeSqlLiteral(tableName)}'
                     AND attribute.attname = '{EscapeSqlLiteral(columnName)}'
                     AND attribute.attidentity = '')
               THEN
                   EXECUTE format(
                       'ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
                       '{EscapeSqlLiteral(tableName)}',
                       '{EscapeSqlLiteral(columnName)}');
               END IF;
           END $$;
           """;

    public static string DropConstraintIfExists(string tableName, string constraintName)
        => $"""
           DO $$
           BEGIN
               IF to_regclass('{EscapeSqlLiteral(tableName)}') IS NOT NULL THEN
                   ALTER TABLE {QuoteIdentifier(tableName)} DROP CONSTRAINT IF EXISTS {QuoteIdentifier(constraintName)};
               END IF;
           END $$;
           """;

    public static string AddColumnIfMissing(string tableName, string columnName, string columnDefinitionSql)
        => $"""
           DO $$
           BEGIN
               IF to_regclass('{EscapeSqlLiteral(tableName)}') IS NOT NULL
                  AND NOT EXISTS (
                       SELECT 1
                       FROM information_schema.columns
                       WHERE table_schema = current_schema()
                         AND table_name = '{EscapeSqlLiteral(tableName)}'
                         AND column_name = '{EscapeSqlLiteral(columnName)}')
               THEN
                   EXECUTE format(
                       'ALTER TABLE %I ADD COLUMN %I {columnDefinitionSql}',
                       '{EscapeSqlLiteral(tableName)}',
                       '{EscapeSqlLiteral(columnName)}');
               END IF;
           END $$;
           """;

    private static string QuoteIdentifier(string identifier)
    {
        var parts = identifier.Split('.', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
        var builder = new StringBuilder();

        for (var index = 0; index < parts.Length; index++)
        {
            if (index > 0)
            {
                builder.Append('.');
            }

            builder.Append('"');
            builder.Append(parts[index].Replace("\"", "\"\"", StringComparison.Ordinal));
            builder.Append('"');
        }

        return builder.ToString();
    }

    private static string EscapeSqlLiteral(string value)
        => value.Replace("'", "''", StringComparison.Ordinal);
}
