// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolNexus.Infrastructure.Data;

#nullable disable

namespace ToolNexus.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ToolNexusContentDbContext))]
    partial class ToolNexusContentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ToolCategories");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ToolContents");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolExampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolExamples");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolFaqEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolFaqs");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolFeatureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolFeatures");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolRelatedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelatedSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolRelated");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolStepEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolSteps");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolUseCaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolContentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToolContentId");

                    b.ToTable("ToolUseCases");
                });



            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolExecutionPolicyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExecutionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxInputSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRequestsPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToolDefinitionId")
                        .IsUnique();

                    b.HasIndex("ToolSlug")
                        .IsUnique();

                    b.ToTable("ToolExecutionPolicies");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolExecutionEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PayloadSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("ToolSlug");

                    b.ToTable("ToolExecutionEvents");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolDefinitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionsCsv")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ToolDefinitions");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolExampleEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("Examples")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolFaqEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("Faq")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolFeatureEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("Features")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolRelatedEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("RelatedTools")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolStepEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("Steps")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolUseCaseEntity", b =>
                {
                    b.HasOne("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", "ToolContent")
                        .WithMany("UseCases")
                        .HasForeignKey("ToolContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolContent");
                });

            modelBuilder.Entity("ToolNexus.Infrastructure.Content.Entities.ToolContentEntity", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("Faq");

                    b.Navigation("Features");

                    b.Navigation("RelatedTools");

                    b.Navigation("Steps");

                    b.Navigation("UseCases");
                });
#pragma warning restore 612, 618
        }
    }
}
