using Microsoft.EntityFrameworkCore;
using Xunit;
using Xunit.Sdk;

namespace ToolNexus.Infrastructure.Tests.Migrations;

public sealed class PostgresMigrationIntegrityTests
{
    [Fact]
    public void ContentMigrations_DoNotUseDirectUnsafeIdentityAlterStatements()
    {
        var migrationDirectory = Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "src", "ToolNexus.Infrastructure", "Data", "Migrations");
        var migrationFiles = Directory.GetFiles(migrationDirectory, "*.cs", SearchOption.TopDirectoryOnly)
            .Where(file => !file.EndsWith(".Designer.cs", StringComparison.Ordinal))
            .ToArray();

        foreach (var file in migrationFiles)
        {
            var content = File.ReadAllText(file);
            Assert.DoesNotContain("migrationBuilder.Sql(@\"ALTER TABLE", content, StringComparison.Ordinal);
            Assert.DoesNotContain("ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY", content, StringComparison.Ordinal);
        }
    }


    [Fact]
    public void ContentMigrations_DoNotUseLegacyAliasIdJoinsWithoutGuards()
    {
        var migrationDirectory = Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "src", "ToolNexus.Infrastructure", "Data", "Migrations");
        var migrationFiles = Directory.GetFiles(migrationDirectory, "*.cs", SearchOption.TopDirectoryOnly)
            .Where(file => !file.EndsWith(".Designer.cs", StringComparison.Ordinal))
            .ToArray();

        foreach (var file in migrationFiles)
        {
            var content = File.ReadAllText(file);
            Assert.DoesNotContain("INNER JOIN execution_runs er ON er.id = es.execution_run_id", content, StringComparison.Ordinal);
            Assert.DoesNotContain("SELECT\n                         es.id,", content, StringComparison.Ordinal);
        }
    }

    [Fact]
    public async Task EmptyDatabase_MigrateTwice_CompletesWithoutPendingMigrations()
    {
        await using var database = await CreatePostgresDatabaseOrSkipAsync();
        await using var context = database.CreateContext();

        await context.Database.MigrateAsync();
        await context.Database.MigrateAsync();

        Assert.Empty(await context.Database.GetPendingMigrationsAsync());
    }

    [Fact]
    public async Task PartiallyBootstrappedSchema_WithMissingConstraints_MigrationRemainsSafe()
    {
        await using var database = await CreatePostgresDatabaseOrSkipAsync();
        await using var context = database.CreateContext();

        await context.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS audit_outbox(id uuid primary key, audit_event_id uuid);");
        await context.Database.ExecuteSqlRawAsync("ALTER TABLE audit_outbox DROP CONSTRAINT IF EXISTS \"FK_audit_outbox_audit_events_AuditEventId\";");

        await context.Database.MigrateAsync();

        Assert.Empty(await context.Database.GetPendingMigrationsAsync());
    }

    [Fact]
    public void ExecutionLedgerMigration_UsesSafeConstraintDrops()
    {
        var migrationFile = Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "src", "ToolNexus.Infrastructure", "Data", "Migrations", "20260225214033_AddExecutionLedger.cs");
        var content = File.ReadAllText(migrationFile);

        Assert.DoesNotContain("DropForeignKey(", content, StringComparison.Ordinal);
        Assert.DoesNotContain("DROP CONSTRAINT \"", content, StringComparison.Ordinal);
        Assert.DoesNotContain("AlterColumn<bool>(\n                name: \"IsExecutionEnabled\"", content, StringComparison.Ordinal);
        Assert.Contains("SafeDropConstraintIfExists", content, StringComparison.Ordinal);
        Assert.Contains("SafeConvertColumnToBoolean", content, StringComparison.Ordinal);
    }

    private static async Task<TestDatabaseInstance> CreatePostgresDatabaseOrSkipAsync()
    {
        try
        {
            return await TestDatabaseInstance.CreateUnmigratedAsync(TestDatabaseProvider.PostgreSql);
        }
        catch (SkipException)
        {
            throw;
        }
        catch
        {
            throw SkipException.ForSkip("PostgreSQL test database unavailable.");
        }
    }
}
